- docs/_layouts/default.html
- docs/reference/Clauses.md
- docs/reference/ConditionalExpressions.md
- docs/reference/Contracts.md
> Added basic ToC structure

- docs/README.md
> (fix) broken links in doc

- README.md
> (fix) broken license link in README

- README.md
> (chore) Add readmedocs badge

- _layouts/default.html
- docs/README.md
- docs/manual/README.md
> (website) Fixes

- .circleci/config.yml
- contribute-to-ergo/developers/README.md
> (chore) Final switch to Coq 8.8.0+Qcert 1.1.0

- .circleci/config.yml
> (chore) Fix to circleCI config

- .circleci/config.yml
> (chore) Limits to 2 parallel jobs in circleCI script

- .github/dco.yml
> (chore) Remove unused config file

- packages/ergo-compiler/test/ergo.js
> (chore) improve test coverage

- packages/ergo-cli/bin/ergoc.js
> (fix) Cleaner error message for ergoc

- docs/README.md
- docs/_layouts/default.html
- docs/manual/Installation.md
> (doc) A few fixes

- .gitignore
- docs/architecture/package-lock.json
- package.json
- packages/ergo-cli/.gitignore
- packages/ergo-cli/package-lock.json
- packages/ergo-compiler/.gitignore
- packages/ergo-compiler/package-lock.json
- packages/ergo-engine/.gitignore
- packages/ergo-engine/package-lock.json
> (chore) Fix license check ; Update npm packages

- examples/latedeliveryandpenalty/logic.ergo
- examples/promissory-note/logic.ergo
- examples/volumediscount/logic.ergo
- packages/ergo-engine/test/workload.json
> (fix) Examples

- CHANGELOG.md
- lerna.json
- mechanization/Version.v
- packages/ergo-cli/.npmignore
- packages/ergo-cli/CHANGELOG.md
- packages/ergo-cli/package.json
- packages/ergo-compiler/CHANGELOG.md
- packages/ergo-compiler/package.json
- packages/ergo-engine/CHANGELOG.md
- packages/ergo-engine/package.json
- Bump version to 0.0.50
- Add .npmignore for ergo-cli
> Release 0.0.50

- scripts/manualrelease.sh
Signed-off-by: Matt Roberts <matt@clause.io>
> Update manual release branch

- README.md
- docs/manual/Overview.md
> (fix) Change documentation link

- .travis/deploy.sh
Signed-off-by: Matt Roberts <matt@clause.io>
> Remove master branch restriction on deploy script

- examples/installment-sale/logic2.ergo
- examples/installment-sale/model2.cto
- packages/ergo-cli/bin/ergo.js
- packages/ergo-cli/lib/commands.js
- packages/ergo-cli/test/commands.js
- packages/ergo-compiler/test/ergo.js
- packages/ergo-engine/test/ergo-engine.js
- packages/ergo-engine/test/workload.json
> (refactor) Cleaner testing code with both response and state

- README.md
> (fix) README logo

- CONTRIBUTING.md
- DEVELOPERS.md
- README.md
- examples/acceptance-of-delivery/request.json
> (doc) Update README

- DEVELOPERS.md
> (doc) Developers instructions

- docs/ergo-lang-expressions.md
Signed-off-by: Joseph J Bambara <jbesq777@gmail.com>
> update language expressions

- website/core/Footer.js
Signed-off-by: Matt Roberts <matt@clause.io>
Fixes https://github.com/accordproject/ergo/issues/243
> Fix links in Doc Footer

- extraction/src/ErgoCompile.ml
- extraction/src/ErgoParser.mly
- extraction/src/ParseString.ml
- extraction/src/ParseString.mli
- extraction/src/ParseUtil.ml
- extraction/src/ParseUtil.mli
> (feat) Add parser API for declarations

- Makefile
- extraction/Makefile
- extraction/ergocoreJS.ml
- mechanization/Common/Utils/EResult.v
- packages/ergo-engine/package.json
- Fix to `make cleanall`
- Add built-in error `TODO_error`
- Longer timeout for JavaScript tests
> Misc cleanup

- Makefile.coq_modules
- mechanization/Common/Utils/EFormat.v
- mechanization/Compiler/ErgoCompiler.v
- mechanization/Compiler/ErgoCompilerDriver.v
- mechanization/Ergo/Lang/ErgoEval.v
- mechanization/Ergo/Lang/ErgoInline.v
I made some of the refactoring changes recommended by Jerome (cf #283 #284).
> Kc refactor eval

- Makefile.coq_modules
- mechanization/Backend/ErgoBackend.v
- mechanization/Compiler/ErgoCompiler.v
- mechanization/Compiler/ErgoDriver.v
- mechanization/ErgoC/Lang/ErgoC.v
- mechanization/ErgoC/Lang/ErgoCEval.v
- mechanization/ErgoC/Lang/ErgoCEvalContext.v
- mechanization/ErgoC/Lang/ErgoCInline.v
- mechanization/ErgoC/Lang/ErgoCSugar.v
- mechanization/ErgoNNRC/Lang/ErgoNNRC.v
- mechanization/Translation/ErgoCtoErgoNNRC.v
- mechanization/Translation/ErgoCtoErgoNNRCType.v
- mechanization/Translation/ErgotoErgoC.v
> (refactor) Module renaming & REPL context

- extraction/ergotop.ml
- mechanization/Common/Utils/EResult.v
- mechanization/Compiler/ErgoDriver.v
> (feat) state reported in repl

- Makefile.coq_modules
- extraction/ergotop.ml
- mechanization/Compiler/ErgoCompiler.v
- mechanization/Compiler/ErgoDriver.v
- mechanization/ErgoC/Lang/ErgoCEval.v
- mechanization/ErgoC/Lang/ErgoCInline.v
- mechanization/Translation/ErgoInlineContext.v
- mechanization/Translation/ErgotoErgoC.v
Inlining uses the new `inline_context` for support.
> (refactor) inlining happens in compiler now

- examples/repl_examples.ergo
- mechanization/ErgoC/Lang/ErgoCEval.v
But it won't work until #313 is fixed.
> (feat) implemented match in eval

- mechanization/Ergo/Lang/ErgoMap.v
as requested by @jeromesimeon in #309
> (feat) map match

- examples/repl_examples.ergo
- extraction/ergotop.ml
P.S. it would be nice if the parser returned an `option decl` rather than a `decl`, and returned `none` in the case of empty string/whitespace/comment
> multiline input in repl

- examples/repl_examples.ergo
- mechanization/ErgoC/Lang/ErgoCEval.v
> (fix) match optionals

- examples/repl_examples.ergo
> (fix) Ouch, broke the REPL tests

- extraction/src/ErgoUtil.ml
> (fix) Does not crash and burn when underlining

- examples/repl_examples.ergo
- examples/repl_examples.result
> (test) Add comparison tests and expected results for REPL

- packages/ergo-cli/bin/ergotop.js
- packages/ergo-cli/package-lock.json
- packages/ergo-cli/package.json
> multiple lines in repl

- ergo.vim/README.txt
- ergo.vim/ftdetect/ergo.vim
- ergo.vim/syntax/ergo.vim
It works with everything in examples.
> added a vim plugin

- package-lock.json
- packages/ergo-cli/.eslintignore
- packages/ergo-cli/index.html
- packages/ergo-cli/lib/ergo-mode.js
- Full CodeMirror-powered text editor with custom Ergo-mode
- Two panes, one for editing the contract and one for experimenting
- Types are underlined in type errors
> Lots of new features in the repl

- .circleci/config.yml
> (fix) Add missing opam packages to circleCI

- examples/typechecked/repl_studentloan.ergo
this is a WIP example for the NEPLS talk
> (doc) new example involving student loans

- .travis.yml
> (fix) over other fix for triggering deployment from a tagged release

- .circleci/config.yml
> (build) Trying a new CircleCI config - not using apt-get

- .circleci/config.yml
> (fix) Missing lerna in new CircleCI script

- .circleci/config.yml
> (fix) Re-enable cache in CircleCI script

- packages/ergo-cli/bin/ergo.js
- packages/ergo-cli/lib/commands.js
- packages/ergo-cli/test/commands.js
> (chore) Remove obsolete ergo compile

- examples/acceptance-of-delivery/request.json
- package-lock.json
- packages/ergo-cli/lib/ergotop-lib.js
> (chore) Refresh ergo-toplib.js

- examples/acceptance-of-delivery/request.json
- package-lock.json
- package.json
> (fix) Pin to safe version of event-stream

- .circleci/config.yml
> (fix) CircleCI configuration update

- DEVELOPERS.md
- README.md
> (fix) README and Copyright 2019

- packages/ergo-engine/test/cucumbers/installmentsale_normal.feature
- packages/ergo-engine/test/cucumbers/step_definitions/stepdefs.js
> (fix) Add support for testing obligations in Cucumber steps

- .travis.yml
- README.md
- package-lock.json
- package.json
> (fix) Add coveralls reporting

- .travis.yml
- .travis/deploy.sh
> (fix) Update deploy scripts

- package-lock.json
- packages/ergo-cli/package.json
- packages/ergo-compiler/package.json
- packages/ergo-engine/package.json
> (chore) Bump Mocha/Chai to latest versions

- .circleci/config.yml
> (fix) CircleCI configuration for opam2

- .circleci/config.yml
> (fix) CircleCI configuration for opam2, ctnd

- .circleci/config.yml
> (fix) CircleCI configuration for opam2 (3)

- .circleci/config.yml
> (fix) CircleCI configuration for opam2 (4)

- .circleci/config.yml
> (fix) CircleCI configuration for opam2 (5)

- .circleci/config.yml
> (fix) CircleCI configuration for opam2 (6)

- .circleci/config.yml
> (fix) CircleCI configuration for opam2 (7)

- .circleci/config.yml
> (fix) CircleCI configuration for opam2 (8)

- .circleci/config.yml
> (fix) CircleCI configuration for opam2 (9)

- .circleci/config.yml
> (fix) CircleCI configuration for opam2 (10)

- .circleci/config.yml
> (fix) CircleCI configuration for opam2 (12)

- .circleci/config.yml
- DEVELOPERS.md
> (chore) Another take at upgrading to opam2

- .circleci/config.yml
> (chore) Add Java support to CircleCI configuration

- .circleci/config.yml
> (fix) Another small tweak to CircleCI script

- examples/libs/geo.ergo
- examples/libs/math.ergo
Contributing initial versions of math and geo libraries as code examples.
In future, these should be packaged and versioned as independent modules.
> Add initial versions of math and geo libraries

- packages/ergo-engine/lib/engine.js
- packages/ergo-engine/lib/util.js
- packages/ergo-engine/test/engine.js
- packages/ergo-engine/test/util.js
> (refactor) Utility functions

- backends/javascript/ergo-runtime.js
> (fix) NaN in JavaScript runtime

- packages/ergo-engine/lib/engine.js
> (fix) Permit resources for relationships during validation

- packages/ergo-compiler/package.json
> (fix) Add missing jsome dependency on ergo-compiler

- package-lock.json
- packages/ergo-compiler/package.json
- packages/ergo-engine/package.json
> (fix) Up Concerto 0.70.1

- package-lock.json
- packages/ergo-cli/extracted/ergotopcore.js
- packages/ergo-cli/package.json
- packages/ergo-compiler/package.json
- packages/ergo-engine/package.json
- packages/ergo-test/package.json
> (fix) Regenerate ergotop

- package-lock.json
- packages/ergo-cli/extracted/ergotopcore.js
- packages/ergo-compiler/lib/templatelogic.js
- packages/ergo-compiler/package.json
- packages/ergo-compiler/test/data/test2.cto
- packages/ergo-compiler/test/data/test3.cto
- packages/ergo-compiler/test/templatelogic.js
> (fix) Add some update support for models and logic

- packages/ergo-compiler/lib/scriptmanager.js
- packages/ergo-compiler/lib/templatelogic.js
- packages/ergo-compiler/test/scriptmanager.js
> (fix) Adjust script manager for new source/target archive support

- packages/ergo-cli/index.html
> (fix) REPL Web page fix

- packages/ergo-compiler/package.json
> (chore) Update debug dependency for consistency with Cicero

- examples/libs/interests.ergo
> (feature) Add small library for interest rate calculation

- package-lock.json
- packages/ergo-compiler/package.json
> (chore) Bump Composer version 0.70.5

- packages/ergo-cli/index.html
> fix(REPL) Update link to Ergo documentation in online REPL

- ergo.emacs/README.md
- ergo.emacs/ergo-mode.el
- ergo.vim/README.md
- ergo.vim/README.txt
- package.json
> feature(emacs) Move emacs mode to main repo

- ergo.emacs/README.md
> fix(emacs) README

- CHARTER.md
- README.md
- Initiate Linux Foundation charter as a markdown file.
- N/A
- N/A
> docs(CHARTER): implement linux foundation charter - I620

- README.md
Signed-off-by: Peter Hunn <peter@peterhunn.com>
> docs(README): add trademark policy - I620

- README.md
Signed-off-by: Aayush Bisen <aayush23101998@outlook.com>
Centered Ergo and Accord Project Logo, adding the Slack badge, adding the License badge
- Centered logos of Ergo and Accord Project in README
- Adding the Slack Badge in README
- Adding the license badge in README
- None
- None
> docs(README): centered logos, adds slack badge, adds license badge

- README.md
<OVERALL SUMMARY OF PULL REQUEST>
- add downloads badge
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #<NUMBER HERE>
- Pull Request #<NUMBER HERE>
> docs(README): add downloads badge - I77

- CONTRIBUTING.md
Signed-off-by: Archit garg4.ag@gmail.com
I found some Improper word choice as well as Improper formatting for that I have made changes and corrected that so, now It will be easier for everyone to read.
Please Merge this
> docs(CONTRIBUTING): grammar updates

- DEVELOPERS.md
fix links to menu 'Writing Documentation' and Lerna
***Obs: There's no issue to this correction***
- Fix some links in DEVELOPERS.md
- *Writing Documentation* line 181
- *Lerna* line 31
> docs(DEVELOPERS): update links

- CONTRIBUTING.md
Changing some small grammar issues.
Signed-off-by: Kewbish <kewbish@gmail.com>
Deleted several commas and added some where necessary.
- Comma addition or deletion
- none
- Issue none
- Pull Request none
> docs(CONTRIBUTING): fix grammar

- DEVELOPERS.md
proper-ed links in the DEVELOPERS.md . 
- removed escape character(\) at multiple places.
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>
- Issue #659 
- Pull Request #661
> refactor(DEVELOPERS): fix broken links - fix issue #659

- README.md
Signed-off-by: Aayush Bisen <aayush23101998@outlook.com>
Updated the Slack badge to "Accord Project - Join Slack" in README.
- Updated the Slack badge in README.
- None
- https://github.com/accordproject/techdocs/issues/78
> docs(README): updated slack badge

- .travis/base.sh
> fix(deploy) Should not rely on TRAVIS_BRANCH when tagging

- README.md
Signed-off-by: Dmitry <daniloff200@gmail.com>
https://github.com/accordproject/techdocs/issues/80#issuecomment-544871864
> fix(readme): fix broken markdown editor link

- DEVELOPERS.md
Signed-off-by: Archit garg4.ag@gmail.com
I found some Improper word choice as well as Improper formatting for that I have made changes and corrected that so, now It will be easier for everyone to read.
Please Merge this
> fix(DEVELOPERS): grammar

- package-lock.json
- packages/ergo-compiler/package.json
> chore(dep) Upgrade to Markus 0.7.2

- package-lock.json
- package.json
- packages/ergo-cli/extracted/ergotopcore.js
- packages/ergo-compiler/package.json
> chore(dep) Upgrade to Concert 0.82.5 & Markus 0.8.0

- packages/ergo-compiler/package.json
> chore(dep) Upgrade to markdown transform 0.9.1

- packages/ergo-compiler/package.json
> chore(dep) Fix to latest Markdown Transform 0.9.2

- .circleci/config.yml
- examples/acceptance-of-delivery/request.json
- examples/promissory-note/data.json
- examples/promissory-note/data2.json
- examples/promissory-note/data3.json
- packages/ergo-cli/test/features/acceptanceofdelivery_normal.feature
- packages/ergo-test/test/features/acceptanceofdelivery_normal.feature
- packages/ergo-test/test/features/fragilegoods_normal.feature
- packages/ergo-test/test/features/promissorynote_simple.feature
- packages/ergo-test/test/features/promissorynote_with_concept_model.feature
- packages/ergo-test/test/features/promissorynote_with_module.feature
Fixes for values in tests, so they pass stricter validation rules https://github.com/accordproject/concerto/issues/157
> fix(test) Various cleanup of atomic values in test data

- package-lock.json
- packages/ergo-cli/extracted/ergotopcore.js
- packages/ergo-compiler/package.json
> chore(dep) Upgrade to Markdown Transform 0.9.4

- package-lock.json
- package.json
- packages/ergo-compiler/package.json
> chore(dep) Upgrade AP dependencies

- packages/ergo-compiler/package.json
> chore(dep) Latest dev version of Markdown Transform

- package-lock.json
- packages/ergo-compiler/package.json
> chore(dep) Remove unused markdown transform deps

- packages/ergo-compiler/test/logicmanager.js
- packages/ergo-compiler/test/scriptmanager.js
> fix(tests) Update tests for latest release

- package-lock.json
- package.json
- packages/ergo-compiler/package.json
> chore(dep) Upgrade to Concerto 0.82.11

- packages/ergo-cli/package.json
- packages/ergo-compiler/package.json
- packages/ergo-engine/package.json
- packages/ergo-test/package.json
Signed-off-by: Aniruddha Shriwant <aniruddhashriwant@gmail.com>
<OVERALL SUMMARY OF PULL REQUEST>
- Added Package Repository Information (directory) in `package.json`<INSERT DESCRIPTION OF CHANGES>
> feat(package): add repository information to package.json

- README.md
Signed-off-by: Aniruddha Shriwant <aniruddhashriwant@gmail.com>
- Updated ergo-compiler link in [Structure of the Code Repository ](https://github.com/accordproject/ergo#structure-of-the-code-repository) section
> fix(Readme): updated ergo-compiler link

- packages/ergo-engine/lib/engine.js
- Fixes engine issue: confusing contract name with contract id
> fix(engine) Lookup contract name from the logic manager

- package-lock.json
- packages/ergo-compiler/lib/apmodelmanager.js
- packages/ergo-compiler/test/logicmanager.js
- scripts/external/jstarget.hbs
- Fixes issues with external models resolution
> fix(compiler) Resolve external models and offline mode

- package-lock.json
- package.json
- packages/ergo-cli/extracted/ergotopcore.js
- packages/ergo-compiler/package.json
- packages/ergo-engine/package.json
- Upgrade to Concerto `1.0.0-alpha.10`
> chore(dep) Upgrade to Concerto 1.0.0-alpha.10

- packages/ergo-cli/index.js
- packages/ergo-cli/lib/commands.js
- packages/ergo-cli/test/commands.js
- packages/ergo-engine/.eslintignore
- packages/ergo-test/.eslintignore
Fixes CLI for `0.22`
- Remove remnants of moment library in Ergo CLI
- Add `currentOffset` option to CLI
> fix(cli) Remove moment library in CLI and add utcOffset option

- .circleci/config.yml
Signed-off-by: Jerome Simeon <Jerome.Simeon@docusign.com>
- Fixed for CircleCI "from source" builds
> fix(build): Attempt to fix CircleCI build

- package-lock.json
- package.json
- packages/ergo-cli/extracted/ergotopcore.js
- packages/ergo-compiler/lib/apmodelmanager.js
- packages/ergo-compiler/lib/compilerexception.js
- packages/ergo-compiler/package.json
- packages/ergo-compiler/test/logicmanager.js
- packages/ergo-compiler/test/script.js
- packages/ergo-engine/package.json
- packages/ergo-engine/test/validateES6.js
- Upgrade to newly released Concerto `2.0.0-alpha.1`
> feature(*): Switch to Concerto 2.0.0-alpha.1

- package-lock.json
- packages/ergo-cli/package.json
> fix(dep): Upgrade yargs

- package-lock.json
- package.json
- packages/ergo-cli/package.json
- packages/ergo-compiler/package.json
- packages/ergo-engine/package.json
- packages/ergo-test/package.json
- Update all `engines` descriptions in package.json files to require node 14
> chore(build): Update engines constraints in all package.json
